---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex-release-testing2
  namespace: servicex-testing-2
spec:
  interval: 1m
  serviceAccountName: servicex-testing-2
  chart:
    spec:
      chart: servicex
      version: '1.0.12'
      sourceRef:
        kind: HelmRepository
        name: servicex-repo
        namespace: servicex-testing-2
      interval: 1m
  values:
    replicaCount: 1
  valuesFrom:
    - kind: Secret
      metadata:
        namespace: servicex-testing-2
      name: servicex-secrets
      key: postgresql-postgres-password
      targetPath: app.postgresql_password
    - kind: Secret
      metadata:
        namespace: servicex-testing-2
      name: servicex-secrets
      key: minio-accesskey
      targetPath: app.minio_accesskey
    - kind: Secret
      metadata:
        namespace: servicex-testing-2
      name: servicex-secrets
      key: minio.secretkey
      targetPath: app.minio_secretkey
    - kind: Secret
      metadata:
        namespace: servicex-testing-2
      name: servicex-secrets
      key: rabbitmq-erlang-cookie
      targetPath: app.rabbitmq_erlang_cookie
    - kind: Secret
      metadata:
        namespace: servicex-testing-2
      name: servicex-secrets
      key: rabbitmq-password
      targetPath: app.rabbitmq_password
        
